# Generated by Django 4.2.7 on 2025-11-28 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_mode', models.CharField(choices=[('pvp', 'Player vs Player'), ('ai', 'Player vs AI')], default='pvp', max_length=10)),
                ('ai_difficulty', models.CharField(blank=True, max_length=10, null=True)),
                ('ai_color', models.CharField(blank=True, max_length=5, null=True)),
                ('board_state', models.TextField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1')),
                ('current_turn', models.CharField(default='white', max_length=5)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for opponent'), ('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='waiting', max_length=20)),
                ('result', models.CharField(choices=[('white_wins', 'White Wins'), ('black_wins', 'Black Wins'), ('draw', 'Draw'), ('ongoing', 'Ongoing')], default='ongoing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('black_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_black', to=settings.AUTH_USER_MODEL)),
                ('white_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_white', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ai_move', models.BooleanField(default=False)),
                ('move_notation', models.CharField(max_length=10)),
                ('san_notation', models.CharField(max_length=10)),
                ('fen_after_move', models.TextField()),
                ('move_number', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='game.game')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['move_number'],
            },
        ),
    ]
